Schema.voices.Add("DispatchRadio", "0", "0", "npc/overwatch/radiovoice/zero.wav")
Schema.voices.Add("DispatchRadio", "1", "1", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("DispatchRadio", "10-0 BEGIN SCAN", "10-0; begin scanning", "npc/overwatch/radiovoice/beginscanning10-0.wav")
Schema.voices.Add("DispatchRadio", "10-103M", "10-103M; disturbance by mentally unfit", "npc/overwatch/radiovoice/disturbancemental10-103m.wav")
Schema.voices.Add("DispatchRadio", "100 CREDITS", "Rank-leaders, reminder: One-hundred sterilized credits qualifies non-mechanical reproduction simulation", "npc/overwatch/radiovoice/reminder100credits.wav")
Schema.voices.Add("DispatchRadio", "148", "148; resisting arrest", "npc/overwatch/radiovoice/resistingpacification148.wav")
Schema.voices.Add("DispatchRadio", "17F", "17f; fugitive detachment", "npc/overwatch/radiovoice/fugitive17f.wav")
Schema.voices.Add("DispatchRadio", "2", "2", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("DispatchRadio", "243", "243; assault on protection-team", "npc/overwatch/radiovoice/assault243.wav")
Schema.voices.Add("DispatchRadio", "27", "27; attempted crime", "npc/overwatch/radiovoice/attemptedcrime27.wav")
Schema.voices.Add("DispatchRadio", "3", "3", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("DispatchRadio", "4", "4", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("DispatchRadio", "404", "404; riot", "npc/overwatch/radiovoice/riot404.wav")
Schema.voices.Add("DispatchRadio", "404 RIOT", "404; riot", "npc/overwatch/radiovoice/riot404.wav")
Schema.voices.Add("DispatchRadio", "404 ZONE", "Four-hundred and four zone", "npc/overwatch/radiovoice/404zone.wav")
Schema.voices.Add("DispatchRadio", "415", "415; civic-disunity", "npc/overwatch/radiovoice/disturbingunity415.wav")
Schema.voices.Add("DispatchRadio", "5", "5", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("DispatchRadio", "507", "507; public non-compliance", "npc/overwatch/radiovoice/publicnoncompliance507.wav")
Schema.voices.Add("DispatchRadio", "51", "51; non-sanctioned arson", "npc/overwatch/radiovoice/nonsanctionedarson51.wav")
Schema.voices.Add("DispatchRadio", "51B", "51B; threat to property", "npc/overwatch/radiovoice/threattoproperty51b.wav")
Schema.voices.Add("DispatchRadio", "6", "6", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("DispatchRadio", "603", "603; unlawful entry", "npc/overwatch/radiovoice/unlawfulentry603.wav")
Schema.voices.Add("DispatchRadio", "62", "62; alarms", "npc/overwatch/radiovoice/alarms62.wav")
Schema.voices.Add("DispatchRadio", "63", "63; criminal trespass", "npc/overwatch/radiovoice/criminaltrespass63.wav")
Schema.voices.Add("DispatchRadio", "63S", "63S; illegal in operation", "npc/overwatch/radiovoice/illegalinoperation63s.wav")
Schema.voices.Add("DispatchRadio", "69", "69; possession of resources", "npc/overwatch/radiovoice/posession69.wav")
Schema.voices.Add("DispatchRadio", "7", "7", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("DispatchRadio", "8", "8", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("DispatchRadio", "9", "9", "npc/overwatch/radiovoice/nine.wav")
Schema.voices.Add("DispatchRadio", "94", "94; weapon", "npc/overwatch/radiovoice/weapon94.wav")
Schema.voices.Add("DispatchRadio", "95", "95; illegal carrying", "npc/overwatch/radiovoice/illegalcarrying95.wav")
Schema.voices.Add("DispatchRadio", "99", "99; reckless operation", "npc/overwatch/radiovoice/recklessoperation99.wav")
Schema.voices.Add("DispatchRadio", "ACCOMPLICES", "Protection-teams, be advised: Accomplices operating in area", "npc/overwatch/radiovoice/accomplicesoperating.wav")
Schema.voices.Add("DispatchRadio", "ACTIVITY", "AirWatch copies no activity in location", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav")
Schema.voices.Add("DispatchRadio", "ADMINISTER", "Administer", "npc/overwatch/radiovoice/administer.wav")
Schema.voices.Add("DispatchRadio", "ALARMS", "62; alarms", "npc/overwatch/radiovoice/alarms62.wav")
Schema.voices.Add("DispatchRadio", "ALL TEAMS", "All teams, respond; code three", "npc/overwatch/radiovoice/allteamsrespondcode3.wav")
Schema.voices.Add("DispatchRadio", "ALL UNITS AT", "All units at", "npc/overwatch/radiovoice/allunitsat.wav")
Schema.voices.Add("DispatchRadio", "ALL UNITS BEGIN", "All units, begin witness sterilization", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav")
Schema.voices.Add("DispatchRadio", "AMPUTATE", "Amputate", "npc/overwatch/radiovoice/amputate.wav")
Schema.voices.Add("DispatchRadio", "AMPUTATION", "Immediate amputation", "npc/overwatch/radiovoice/immediateamputation.wav")
Schema.voices.Add("DispatchRadio", "ANTICITIZEN", "Anti-citizen", "npc/overwatch/radiovoice/anticitizen.wav")
Schema.voices.Add("DispatchRadio", "ANTIFATIGUE", "Anti-fatigue ration is now: Three miligrams", "npc/overwatch/radiovoice/antifatigueration3mg.wav")
Schema.voices.Add("DispatchRadio", "APPLY", "Apply", "npc/overwatch/radiovoice/apply.wav")
Schema.voices.Add("DispatchRadio", "APPLY PRESSURE", "All units, apply forward pressure", "npc/overwatch/radiovoice/allunitsapplyforwardpressure.wav")
Schema.voices.Add("DispatchRadio", "ARE CHARGED WITH", "You are charged with terminal violations: 148, 243, 245", "npc/overwatch/radiovoice/youarechargedwithterminal.wav")
Schema.voices.Add("DispatchRadio", "ATTENTION", "Attention", "npc/overwatch/radiovoice/attention.wav")
Schema.voices.Add("DispatchRadio", "BLOCK", "Block", "npc/overwatch/radiovoice/block.wav")
Schema.voices.Add("DispatchRadio", "BOL 243", "All units, BOL for 243 suspect", "npc/overwatch/radiovoice/allunitsbolfor243suspect.wav")
Schema.voices.Add("DispatchRadio", "CANALBLOCK", "Canalblock", "npc/overwatch/radiovoice/canalblock.wav")
Schema.voices.Add("DispatchRadio", "CAPITAL MALCOMPLIANCE", "Capital malcompliance", "npc/overwatch/radiovoice/capitalmalcompliance.wav")
Schema.voices.Add("DispatchRadio", "CAUTERIZE", "Cauterize", "npc/overwatch/radiovoice/cauterize.wav")
Schema.voices.Add("DispatchRadio", "CHARGED WITH", "Attention; you have been charged with", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav")
Schema.voices.Add("DispatchRadio", "CITIZEN", "Citizen", "npc/overwatch/radiovoice/citizen.wav")
Schema.voices.Add("DispatchRadio", "CLOSING ON", "Officer closing on suspect", "npc/overwatch/radiovoice/officerclosingonsuspect.wav")
Schema.voices.Add("DispatchRadio", "COMMUNAL UNREST", "Promoting communal unrest", "npc/overwatch/radiovoice/promotingcommunalunrest.wav")
Schema.voices.Add("DispatchRadio", "COMPLETE SENTENCING", "All protection-team units: Complete sentencing at will", "npc/overwatch/radiovoice/completesentencingatwill.wav")
Schema.voices.Add("DispatchRadio", "CONDEMNED", "Condemned zone", "npc/overwatch/radiovoice/condemnedzone.wav")
Schema.voices.Add("DispatchRadio", "CONFIRM UPI", "Team, confirm UPI alert", "npc/overwatch/radiovoice/confirmupialert.wav")
Schema.voices.Add("DispatchRadio", "CONTROLSECTION", "Politi-control section", "npc/overwatch/radiovoice/controlsection.wav")
Schema.voices.Add("DispatchRadio", "DEFENDER", "DEFENDER", "npc/overwatch/radiovoice/defender.wav")
Schema.voices.Add("DispatchRadio", "DESERVICED", "Unit deserviced", "npc/overwatch/radiovoice/unitdeserviced.wav")
Schema.voices.Add("DispatchRadio", "DESTRUCTION", "Destruction of corporal social-protection units", "npc/overwatch/radiovoice/destrutionofcpt.wav")
Schema.voices.Add("DispatchRadio", "DISASSOCIATION", "Disassociation from the civic populace", "npc/overwatch/radiovoice/disassociationfromcivic.wav")
Schema.voices.Add("DispatchRadio", "DISENGAGED", "647-E disengaged from workforce", "npc/overwatch/radiovoice/disengaged647e.wav")
Schema.voices.Add("DispatchRadio", "DISTRIBUTION BLOCK", "Distribution block", "npc/overwatch/radiovoice/distributionblock.wav")
Schema.voices.Add("DispatchRadio", "DOCUMENT", "Document", "npc/overwatch/radiovoice/document.wav")
Schema.voices.Add("DispatchRadio", "EIGHT", "Eight", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("DispatchRadio", "EXAMINE", "Examine", "npc/overwatch/radiovoice/examine.wav")
Schema.voices.Add("DispatchRadio", "EXTERNAL JURISDICTION", "External jurisdiction", "npc/overwatch/radiovoice/externaljurisdiction.wav")
Schema.voices.Add("DispatchRadio", "FAILURE TO COMPLY", "Failure to comply with the civil will", "npc/overwatch/radiovoice/failuretocomply.wav")
Schema.voices.Add("DispatchRadio", "FINAL SENTENCING", "Prepare for final sentencing", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav")
Schema.voices.Add("DispatchRadio", "FINAL VERDICT", "Final verdict administered", "npc/overwatch/radiovoice/finalverdictadministered.wav")
Schema.voices.Add("DispatchRadio", "FIVE", "Five", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("DispatchRadio", "FOUR", "Four", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("DispatchRadio", "HERO", "HERO", "npc/overwatch/radiovoice/hero.wav")
Schema.voices.Add("DispatchRadio", "HIGH PRIORITY", "High-priority region", "npc/overwatch/radiovoice/highpriorityregion.wav")
Schema.voices.Add("DispatchRadio", "IN PROGRESS", "In-progress", "npc/overwatch/radiovoice/inprogress.wav")
Schema.voices.Add("DispatchRadio", "INDUSTRIAL ZONE", "Industrial zone", "npc/overwatch/radiovoice/industrialzone.wav")
Schema.voices.Add("DispatchRadio", "INFECTION", "Infection", "npc/overwatch/radiovoice/infection.wav")
Schema.voices.Add("DispatchRadio", "INFESTED", "Infested zone", "npc/overwatch/radiovoice/infestedzone.wav")
Schema.voices.Add("DispatchRadio", "INJECT", "Inject", "npc/overwatch/radiovoice/inject.wav")
Schema.voices.Add("DispatchRadio", "INNOCULATE", "Innoculate", "npc/overwatch/radiovoice/innoculate.wav")
Schema.voices.Add("DispatchRadio", "INTERCEDE", "Intercede", "npc/overwatch/radiovoice/intercede.wav")
Schema.voices.Add("DispatchRadio", "INTERLOCK", "Interlock", "npc/overwatch/radiovoice/interlock.wav")
Schema.voices.Add("DispatchRadio", "INVESTIGATE", "Investigate", "npc/overwatch/radiovoice/investigate.wav")
Schema.voices.Add("DispatchRadio", "INVESTIGATE REPORT", "Investigate and report", "npc/overwatch/radiovoice/investigateandreport.wav")
Schema.voices.Add("DispatchRadio", "IS NOW", "Is now", "npc/overwatch/radiovoice/isnow.wav")
Schema.voices.Add("DispatchRadio", "IS NOW 187", "Suspect is now 187", "npc/overwatch/radiovoice/suspectisnow187.wav")
Schema.voices.Add("DispatchRadio", "ISOLATE", "Isolate", "npc/overwatch/radiovoice/isolate.wav")
Schema.voices.Add("DispatchRadio", "JUDGED GUILTY", "You are judged guilty by civil-protection teams", "npc/overwatch/radiovoice/youarejudgedguilty.wav")
Schema.voices.Add("DispatchRadio", "JURY", "JURY", "npc/overwatch/radiovoice/jury.wav")
Schema.voices.Add("DispatchRadio", "KING", "KING", "npc/overwatch/radiovoice/king.wav")
Schema.voices.Add("DispatchRadio", "LINE", "LINE", "npc/overwatch/radiovoice/line.wav")
Schema.voices.Add("DispatchRadio", "LOCK", "Lock", "npc/overwatch/radiovoice/lock.wav")
Schema.voices.Add("DispatchRadio", "LOCKDOWN LOCATION", "Protection-team, lock down your location; sacrifice code", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav")
Schema.voices.Add("DispatchRadio", "LOST BIOSIGNAL", "Lost biosignal for protection-team unit", "npc/overwatch/radiovoice/lostbiosignalforunit.wav")
Schema.voices.Add("DispatchRadio", "MARGINAL", "Notice, protection-teams; civic politi-stabilization index is marginal", "npc/overwatch/radiovoice/politistablizationmarginal.wav")
Schema.voices.Add("DispatchRadio", "MEMORY REPLACEMENT", "Reminder: Memory-replacement is the first step towards rank privileges", "npc/overwatch/radiovoice/remindermemoryreplacement.wav")
Schema.voices.Add("DispatchRadio", "MISCOUNT", "AirWatch reports possible miscount", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav")
Schema.voices.Add("DispatchRadio", "NINE", "Nine", "npc/overwatch/radiovoice/nine.wav")
Schema.voices.Add("DispatchRadio", "NONCITIZEN", "Non-citizen", "npc/overwatch/radiovoice/noncitizen.wav")
Schema.voices.Add("DispatchRadio", "NONCOHESIVE", "Engaging protection-team is noncohesive", "npc/overwatch/radiovoice/engagingteamisnoncohesive.wav")
Schema.voices.Add("DispatchRadio", "NOPATROL", "No patrol region", "npc/overwatch/radiovoice/nonpatrolregion.wav")
Schema.voices.Add("DispatchRadio", "OFFICER AT", "Officer at", "npc/overwatch/radiovoice/officerat.wav")
Schema.voices.Add("DispatchRadio", "OFFWORLD", "Permanent off-world service assignment", "npc/overwatch/radiovoice/permanentoffworld.wav")
Schema.voices.Add("DispatchRadio", "ONE", "One", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("DispatchRadio", "PATROL", "PATROL", "npc/overwatch/radiovoice/patrol.wav")
Schema.voices.Add("DispatchRadio", "PATROL1", "Patrol", "npc/overwatch/radiovoice/patrol.wav")
Schema.voices.Add("DispatchRadio", "PREMATURE", "Premature mission termination will result in", "npc/overwatch/radiovoice/prematuremissiontermination.wav")
Schema.voices.Add("DispatchRadio", "PREPARE INNOCULATE", "All local protection-team units, prepare to innoculate", "npc/overwatch/radiovoice/preparetoinnoculate.wav")
Schema.voices.Add("DispatchRadio", "PREPARE VERDICT", "Prepare to receive verdict", "npc/overwatch/radiovoice/preparetoreceiveverdict.wav")
Schema.voices.Add("DispatchRadio", "PRESERVE", "Preserve", "npc/overwatch/radiovoice/preserve.wav")
Schema.voices.Add("DispatchRadio", "PRESSURE", "Pressure", "npc/overwatch/radiovoice/pressure.wav")
Schema.voices.Add("DispatchRadio", "PRODUCTION BLOCK", "Production-block", "npc/overwatch/radiovoice/productionblock.wav")
Schema.voices.Add("DispatchRadio", "PROSECUTE", "Prosecute", "npc/overwatch/radiovoice/prosecute.wav")
Schema.voices.Add("DispatchRadio", "QUICK", "QUICK", "npc/overwatch/radiovoice/quick.wav")
Schema.voices.Add("DispatchRadio", "RANK POINTS", "Fifty percent rank-points", "npc/overwatch/radiovoice/halfrankpoints.wav")
Schema.voices.Add("DispatchRadio", "RECALIBRATE", "Teams: Recalibrate socio-scan", "npc/overwatch/radiovoice/recalibratesocioscan.wav")
Schema.voices.Add("DispatchRadio", "RECEIVING CONFLICTING", "We are receiving conflicting data", "npc/overwatch/radiovoice/recievingconflictingdata.wav")
Schema.voices.Add("DispatchRadio", "REINFORCEMENT CODE 3", "Reinforcement teams, code three", "npc/overwatch/radiovoice/reinforcementteamscode3.wav")
Schema.voices.Add("DispatchRadio", "REMAINING CONTAIN", "Remaining units, contain", "npc/overwatch/radiovoice/remainingunitscontain.wav")
Schema.voices.Add("DispatchRadio", "REPORT ON", "Local protection-team units, report on", "npc/overwatch/radiovoice/reporton.wav")
Schema.voices.Add("DispatchRadio", "REPORT PLEASE", "Report, please", "npc/overwatch/radiovoice/reportplease.wav")
Schema.voices.Add("DispatchRadio", "REPORT RATIOS", "Attention, stabilization-team leaders; report deserviced units to sterilized body-count ratios for reinforcement reward or removal processing", "npc/overwatch/radiovoice/leadersreportratios.wav")
Schema.voices.Add("DispatchRadio", "REPORT STATUS", "Local civil-protection teams; report status", "npc/overwatch/radiovoice/teamsreportstatus.wav")
Schema.voices.Add("DispatchRadio", "REPRODUCTION CREDITS", "Fifty percent reproduction-credits", "npc/overwatch/radiovoice/halfreproductioncredits.wav")
Schema.voices.Add("DispatchRadio", "REPURPOSED", "Repurposed area", "npc/overwatch/radiovoice/repurposedarea.wav")
Schema.voices.Add("DispatchRadio", "RESIDENTIAL", "Residential block", "npc/overwatch/radiovoice/residentialblock.wav")
Schema.voices.Add("DispatchRadio", "RESPOND", "Respond", "npc/overwatch/radiovoice/respond.wav")
Schema.voices.Add("DispatchRadio", "RESTRICT", "Restrict", "npc/overwatch/radiovoice/restrict.wav")
Schema.voices.Add("DispatchRadio", "RESTRICTED BLOCK", "Restricted block", "npc/overwatch/radiovoice/restrictedblock.wav")
Schema.voices.Add("DispatchRadio", "RESTRICTED INCURSION", "Restricted incursion in-progress", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav")
Schema.voices.Add("DispatchRadio", "RETURN CODE 12", "All units, return to code twelve", "npc/overwatch/radiovoice/allunitsreturntocode12.wav")
Schema.voices.Add("DispatchRadio", "REWARD NOTICE", "Reward-notice, protection-team member: Your family cohesion is preserved", "npc/overwatch/radiovoice/rewardnotice.wav")
Schema.voices.Add("DispatchRadio", "ROLLER", "ROLLER", "npc/overwatch/radiovoice/roller.wav")
Schema.voices.Add("DispatchRadio", "SEARCH", "Search", "npc/overwatch/radiovoice/search.wav")
Schema.voices.Add("DispatchRadio", "SEVEN", "Seven", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("DispatchRadio", "SIX", "Six", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("DispatchRadio", "SOCIAL FRACTURE", "Social fracture in-progress; respond", "npc/overwatch/radiovoice/socialfractureinprogress.wav")
Schema.voices.Add("DispatchRadio", "SOCIOCIDAL", "Divisive sociocidal counter-obeyance", "npc/overwatch/radiovoice/devisivesociocidal.wav")
Schema.voices.Add("DispatchRadio", "SOCIOCIDE", "Sociocide", "npc/overwatch/radiovoice/sociocide.wav")
Schema.voices.Add("DispatchRadio", "SOCIOSTABILIZATION RESTORED", "Sociostabilization restored", "npc/overwatch/radiovoice/sociostabilizationrestored.wav")
Schema.voices.Add("DispatchRadio", "STABILIZATION JURISDICTION", "Stabilization jurisdiction", "npc/overwatch/radiovoice/stabilizationjurisdiction.wav")
Schema.voices.Add("DispatchRadio", "STATIONBLOCK", "Station-block", "npc/overwatch/radiovoice/stationblock.wav")
Schema.voices.Add("DispatchRadio", "STATUS ON 243", "All units, report status on 243 suspect", "npc/overwatch/radiovoice/statuson243suspect.wav")
Schema.voices.Add("DispatchRadio", "STERILIZE", "Sterilize", "npc/overwatch/radiovoice/sterilize.wav")
Schema.voices.Add("DispatchRadio", "STORMSYSTEM", "Stormsystem", "npc/overwatch/radiovoice/stormsystem.wav")
Schema.voices.Add("DispatchRadio", "SUBJECT", "Subject", "npc/overwatch/radiovoice/subject.wav")
Schema.voices.Add("DispatchRadio", "SUSPECT VERDICT CODE", "Suspect is judged MALIGNANT; verdict-code is", "npc/overwatch/radiovoice/suspectmalignantverdictcodeis.wav")
Schema.voices.Add("DispatchRadio", "SUSPEND", "Suspend", "npc/overwatch/radiovoice/suspend.wav")
Schema.voices.Add("DispatchRadio", "SUSPEND NEGOTIATIONS", "Suspend negotiations", "npc/overwatch/radiovoice/suspendnegotiations.wav")
Schema.voices.Add("DispatchRadio", "SWITCH TAC 3", "All units, switch comm to TAC-3", "npc/overwatch/radiovoice/switchcomtotac3.wav")
Schema.voices.Add("DispatchRadio", "SWITCH TAC 5", "All units, switch comm to TAC-5 and report into command-point", "npc/overwatch/radiovoice/switchtotac5reporttocp.wav")
Schema.voices.Add("DispatchRadio", "TAP", "TAP", "npc/overwatch/radiovoice/.wav")
Schema.voices.Add("DispatchRadio", "TERMINAL PROSECUTION", "Terminal prosecution", "npc/overwatch/radiovoice/terminalprosecution.wav")
Schema.voices.Add("DispatchRadio", "TERMINAL RESTRICTION", "Terminal restriction zone", "npc/overwatch/radiovoice/terminalrestrictionzone.wav")
Schema.voices.Add("DispatchRadio", "TERMINAL VERDICT", "All units, deliver terminal verdict immediately", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav")
Schema.voices.Add("DispatchRadio", "THREE", "Three", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("DispatchRadio", "TRANSITBLOCK", "Transitblock", "npc/overwatch/radiovoice/transitblock.wav")
Schema.voices.Add("DispatchRadio", "TREAT OUTBREAK", "Stabilization-team; failure to treat identified local outbreak will forsee recall and recycle", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav")
Schema.voices.Add("DispatchRadio", "TWO", "Two", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("DispatchRadio", "UNION", "UNION", "npc/overwatch/radiovoice/union.wav")
Schema.voices.Add("DispatchRadio", "UNIT DOWN AT", "Unit down at", "npc/overwatch/radiovoice/unitdownat.wav")
Schema.voices.Add("DispatchRadio", "UPI", "UPI", "npc/overwatch/radiovoice/upi.wav")
Schema.voices.Add("DispatchRadio", "VERDICT CODE IS", "All units; verdict-code is", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav")
Schema.voices.Add("DispatchRadio", "VERDICT CODE SUSPECT", "All units, verdict-code on suspect", "npc/overwatch/radiovoice/allunitsverdictcodeonsuspect.wav")
Schema.voices.Add("DispatchRadio", "VICE", "VICE", "npc/overwatch/radiovoice/vice.wav")
Schema.voices.Add("DispatchRadio", "VICTOR", "VICTOR", "npc/overwatch/radiovoice/victor.wav")
Schema.voices.Add("DispatchRadio", "VIOLATION CIVIC TRUST", "Violation of civic trust", "npc/overwatch/radiovoice/violationofcivictrust.wav")
Schema.voices.Add("DispatchRadio", "WORKFORCE INTAKE", "Workforce intake hub", "npc/overwatch/radiovoice/workforceintake.wav")
Schema.voices.Add("DispatchRadio", "XRAY", "XRAY", "npc/overwatch/radiovoice/xray.wav")
Schema.voices.Add("DispatchRadio", "YELLOW", "YELLOW", "npc/overwatch/radiovoice/yellow.wav")
Schema.voices.Add("DispatchRadio", "ZERO", "Zero", "npc/overwatch/radiovoice/zero.wav")