Schema.voices.Add("UniversalUnion", ",", ",", "npc/metropolice/vo/_comma.wav")
Schema.voices.Add("UniversalUnion", "ZERO", "Zero", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("UniversalUnion", "ONE", "One", "npc/metropolice/vo/one.wav")
Schema.voices.Add("UniversalUnion", "TWO", "Two", "npc/metropolice/vo/two.wav")
Schema.voices.Add("UniversalUnion", "THREE", "Three", "npc/metropolice/vo/three.wav")
Schema.voices.Add("UniversalUnion", "FOUR", "Four", "npc/metropolice/vo/four.wav")
Schema.voices.Add("UniversalUnion", "FIVE", "Five", "npc/metropolice/vo/five.wav")
Schema.voices.Add("UniversalUnion", "SIX", "Six", "npc/metropolice/vo/six.wav")
Schema.voices.Add("UniversalUnion", "SEVEN", "Seven", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("UniversalUnion", "EIGHT", "Eight", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("UniversalUnion", "NINE", "Nine", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("UniversalUnion", "TEN", "Ten", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("UniversalUnion", "ELEVEN", "Eleven", "npc/metropolice/vo/eleven.wav")
Schema.voices.Add("UniversalUnion", "TWELVE", "Twelve", "npc/metropolice/vo/twelve.wav")
Schema.voices.Add("UniversalUnion", "THIRTEEN", "Thirteen", "npc/metropolice/vo/thirteen.wav")
Schema.voices.Add("UniversalUnion", "FOURTEEN", "Fourteen", "npc/metropolice/vo/fourteen.wav")
Schema.voices.Add("UniversalUnion", "FIFTEEN", "Fifteen", "npc/metropolice/vo/fifteen.wav")
Schema.voices.Add("UniversalUnion", "SIXTEEN", "Sixteen", "npc/metropolice/vo/sixteen.wav")
Schema.voices.Add("UniversalUnion", "SEVENTEEN", "Seventeen", "npc/metropolice/vo/seventeen.wav")
Schema.voices.Add("UniversalUnion", "EIGHTEEN", "Eighteen", "npc/metropolice/vo/eighteen.wav")
Schema.voices.Add("UniversalUnion", "NINETEEN", "Nineteen", "npc/metropolice/vo/nineteen.wav")
Schema.voices.Add("UniversalUnion", "TWENTY", "Twenty", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("UniversalUnion", "THIRTY", "Thirty", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("UniversalUnion", "FOURTY", "Fourty", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("UniversalUnion", "FIFTY", "Fifty", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("UniversalUnion", "SIXTY", "Sixty", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("UniversalUnion", "SEVENTY", "Seventy", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("UniversalUnion", "EIGHTY", "Eighty", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("UniversalUnion", "NINETY", "Ninety", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("UniversalUnion", "ONE HUNDRED", "One-hundred", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("UniversalUnion", "TWO HUNDRED", "Two-hundred", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("UniversalUnion", "THREE HUNDRED", "Three-hundred", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("UniversalUnion", "0", "0", "npc/combine_soldier/vo/zero.wav")
Schema.voices.Add("UniversalUnion", "1", "1", "npc/combine_soldier/vo/one.wav")
Schema.voices.Add("UniversalUnion", "2", "2", "npc/combine_soldier/vo/two.wav")
Schema.voices.Add("UniversalUnion", "3", "3", "npc/combine_soldier/vo/three.wav")
Schema.voices.Add("UniversalUnion", "4", "4", "npc/combine_soldier/vo/four.wav")
Schema.voices.Add("UniversalUnion", "5", "5", "npc/combine_soldier/vo/five.wav")
Schema.voices.Add("UniversalUnion", "6", "6", "npc/combine_soldier/vo/six.wav")
Schema.voices.Add("UniversalUnion", "7", "7", "npc/combine_soldier/vo/seven.wav")
Schema.voices.Add("UniversalUnion", "8", "8", "npc/combine_soldier/vo/eight.wav")
Schema.voices.Add("UniversalUnion", "9", "9", "npc/combine_soldier/vo/niner.wav")
Schema.voices.Add("UniversalUnion", "10", "10.", "npc/combine_soldier/vo/ten.wav")
Schema.voices.Add("UniversalUnion", "11", "11.", "npc/combine_soldier/vo/eleven.wav")
Schema.voices.Add("UniversalUnion", "12", "12.", "npc/combine_soldier/vo/twelve.wav")
Schema.voices.Add("UniversalUnion", "13", "13", "npc/combine_soldier/vo/thirteen.wav")
Schema.voices.Add("UniversalUnion", "14", "14", "npc/combine_soldier/vo/fourteen.wav")
Schema.voices.Add("UniversalUnion", "15", "15", "npc/combine_soldier/vo/fifteen.wav")
Schema.voices.Add("UniversalUnion", "16", "16", "npc/combine_soldier/vo/sixteen.wav")
Schema.voices.Add("UniversalUnion", "17", "17", "npc/combine_soldier/vo/seventeen.wav")
Schema.voices.Add("UniversalUnion", "18", "18", "npc/combine_soldier/vo/eighteen.wav")
Schema.voices.Add("UniversalUnion", "19", "19", "npc/combine_soldier/vo/nineteen.wav")
Schema.voices.Add("UniversalUnion", "20", "20", "npc/combine_soldier/vo/twenty.wav")
Schema.voices.Add("UniversalUnion", "30", "30", "npc/combine_soldier/vo/thirty.wav")
Schema.voices.Add("UniversalUnion", "40", "40", "npc/combine_soldier/vo/fourty.wav")
Schema.voices.Add("UniversalUnion", "50", "50", "npc/combine_soldier/vo/fifty.wav")
Schema.voices.Add("UniversalUnion", "60", "60", "npc/combine_soldier/vo/sixty.wav")
Schema.voices.Add("UniversalUnion", "70", "70", "npc/combine_soldier/vo/seventy.wav")
Schema.voices.Add("UniversalUnion", "80", "80", "npc/combine_soldier/vo/eighty.wav")
Schema.voices.Add("UniversalUnion", "90", "90", "npc/combine_soldier/vo/ninety.wav")
Schema.voices.Add("UniversalUnion", "100", "100", "npc/combine_soldier/vo/onehundred.wav")
Schema.voices.Add("UniversalUnion", "200", "200", "npc/combine_soldier/vo/twohundred.wav")
Schema.voices.Add("UniversalUnion", "300", "300", "npc/combine_soldier/vo/threehundred.wav")
Schema.voices.Add("UniversalUnion", "10-0 HUNTING", "10-0, 10-0; viscerator is hunting!.", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("UniversalUnion", "10-103 TAG", "Possible 10-103, my location, alert TAG units!.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("UniversalUnion", "10-14 DUTY", "Holding on 10-14 duty; at code four.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("UniversalUnion", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("UniversalUnion", "10-25 SUSPECT", "Any unit, report in with 10-25 as suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("UniversalUnion", "10-30 RESPONDING", "I have a 10-30, my 10-20; responding, code two.", "npc/metropolice/vo/ihave10-30my10-20responding.wav")
Schema.voices.Add("UniversalUnion", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("UniversalUnion", "10-8 STANDING BY", "10-8; standing by.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("UniversalUnion", "10-8", "Unit is on-duty; 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("UniversalUnion", "10-91D COUNT", "10-91d count is.", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("UniversalUnion", "10-97 GOA", "10-97; that suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("UniversalUnion", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("UniversalUnion", "10-99", "Officer down, I am 10-99; I repeat, I am 10-99!", "npc/metropolice/vo/officerdowniam10-99.wav")
Schema.voices.Add("UniversalUnion", "11-44 INBOUND", "Get that 11-44 inbound; we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("UniversalUnion", "11-99", "11-99; officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("UniversalUnion", "34S AT", "All units, BOL; we have 34-S at..", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("UniversalUnion", "404", "404 zone.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("UniversalUnion", "408 AT LOCATION", "I've got a 408 here at location.", "npc/metropolice/vo/ivegot408hereatlocation.wav")
Schema.voices.Add("UniversalUnion", "415B", "Is 415b.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("UniversalUnion", "603", "603, unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("UniversalUnion", "63", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("UniversalUnion", "A GRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("UniversalUnion", "ACQUIRING", "Acquiring on visual.", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("UniversalUnion", "ADMINISTER", "Administer.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("UniversalUnion", "ADW", "Confirmed as ADW on that suspect, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("UniversalUnion", "AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("UniversalUnion", "AFFIRMATIVE2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav")
Schema.voices.Add("UniversalUnion", "AIRWATCH 505", "Dispatch, we need AirWatch; subject is 505.", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("UniversalUnion", "AIRWATCH TAG", "I have a 10-107 here; send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("UniversalUnion", "ALERT", "Alert one!", "npc/combine_soldier/vo/alert1.wav")
Schema.voices.Add("UniversalUnion", "ALL UNITS MOVE IN", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("UniversalUnion", "AMPUTATE", "Amputate", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("UniversalUnion", "ANTI CITIZEN ONE", "Anti-Citizen One.", "npc/combine_soldier/vo/anticitizenone.wav")
Schema.voices.Add("UniversalUnion", "ANTICITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("UniversalUnion", "APEX", "APEX.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("UniversalUnion", "APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("UniversalUnion", "ARREST POSITIONS", "All units, move to arrest positions.", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("UniversalUnion", "ASSAULT POINT SECURED", "Assault-point secured; advance.", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("UniversalUnion", "AT CHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("UniversalUnion", "AT CODE", "Is at code.", "npc/combine_soldier/vo/isatcode.wav")
Schema.voices.Add("UniversalUnion", "AT LOCATION REPORT", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("UniversalUnion", "BACK ME UP", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("UniversalUnion", "BACK UP", "Back up!", "vo/trainyard/ba_backup.wav")
Schema.voices.Add("UniversalUnion", "BACKUP", "Backup!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("UniversalUnion", "BEARING", "Bearing.", "npc/combine_soldier/vo/bearing.wav")
Schema.voices.Add("UniversalUnion", "BELIEVE THAT", "You expect me to believe that?", "npc/metropolice/mc1ans_youexpectme.wav")
Schema.voices.Add("UniversalUnion", "BELIEVE", "Believe what you want.", "npc/metropolice/mc1ans_believewhatyouwant.wav")
Schema.voices.Add("UniversalUnion", "BELLYACHING", "Quit 'yer bellyaching!", "npc/metropolice/mc1ans_bellyaching.wav")
Schema.voices.Add("UniversalUnion", "BETTER THINGS TO DO", "I've got better things to do.", "npc/metropolice/mc1que_betterthings.wav")
Schema.voices.Add("UniversalUnion", "BIOTIC HERE", "We got an outland biotic in here.", "npc/metropolice/vo/outlandbioticinhere.wav")
Schema.voices.Add("UniversalUnion", "BLADE", "BLADE.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("UniversalUnion", "BLEEDING", "Suspect is bleeding from multiple wounds.", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("UniversalUnion", "BLIP", "Catch that blip on the stabilization readout.", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("UniversalUnion", "BLOCK HOLDING", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("UniversalUnion", "BLOCK", "Block.", "npc/metropolice/vo/block.wav")
Schema.voices.Add("UniversalUnion", "BODYPACK", "Bodypack holding!", "npc/combine_soldier/vo/bodypackholding.wav")
Schema.voices.Add("UniversalUnion", "BOL 243", "CP, we need AirWatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("UniversalUnion", "BOOMER", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("UniversalUnion", "BOUNCER", "Bouncer, bouncer!", "npc/combine_soldier/vo/bouncerbouncer.wav")
Schema.voices.Add("UniversalUnion", "BREAK COVER", "Break his cover.", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("UniversalUnion", "BUGS LOOSE", "We have bugs on the loose.", "npc/metropolice/vo/bugsontheloose.wav")
Schema.voices.Add("UniversalUnion", "BUGS", "Bugs.", "npc/metropolice/vo/bugs.wav")
Schema.voices.Add("UniversalUnion", "CAN1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("UniversalUnion", "CAN2", "Pick. up. the. can.", "npc/metropolice/vo/pickupthecan2.wav")
Schema.voices.Add("UniversalUnion", "CAN3", "I said pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("UniversalUnion", "CAN4", "Now, put it in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("UniversalUnion", "CAN5", "I said put it in the trash can!", "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("UniversalUnion", "CAN6", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("UniversalUnion", "CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("UniversalUnion", "CANALBLOCK", "Canal block.", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("UniversalUnion", "CAREER CHOICE", "Yep, this was definitely the best career choice I ever made.", "npc/metropolice/mc1que_career.wav")
Schema.voices.Add("UniversalUnion", "CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("UniversalUnion", "CHECK MISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("UniversalUnion", "CHECKPOINTS", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("UniversalUnion", "CITIZEN SUMMONED", "Reporting citizen summoned to voluntary conscription for general public service detail; T94-322.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("UniversalUnion", "CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("UniversalUnion", "CLASSIFY DB", "Classify subject name as 'DB', this block ready for clean-out.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("UniversalUnion", "CLEANED", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("UniversalUnion", "CLEANUP", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav")
Schema.voices.Add("UniversalUnion", "CLEAR CODE 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("UniversalUnion", "CLOSE ON SUSPECT", "All units, close on suspect.", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("UniversalUnion", "CLOSING", "Closing.", "npc/combine_soldier/vo/closing.wav")
Schema.voices.Add("UniversalUnion", "CLOSING2", "Closing.", "npc/combine_soldier/vo/closing2.wav")
Schema.voices.Add("UniversalUnion", "CODE 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("UniversalUnion", "CODE 2", "All units, code two.", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("UniversalUnion", "CODE 3", "Officer down; request all units code three to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("UniversalUnion", "CODE 7", "Code seven.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("UniversalUnion", "COME WITH ME", "You, citizen! Come with me.", "vo/trainyard/ba_youcomewith.wav")
Schema.voices.Add("UniversalUnion", "CONDEMNED", "Condemned zone.", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("UniversalUnion", "CONTACT 243", "Contact with 243 suspect; my 10-20 is..", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("UniversalUnion", "CONTACT CONFIRM", "Contact confirmed!", "npc/combine_soldier/vo/contactconfim.wav")
Schema.voices.Add("UniversalUnion", "CONTACT CONFIRM2", "Contact confirmed, prosecuting!", "npc/combine_soldier/vo/contactconfirmprosecuting.wav")
Schema.voices.Add("UniversalUnion", "CONTACT PRIORITY", "I have contact with a priority two.", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("UniversalUnion", "CONTACT", "Contact!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("UniversalUnion", "CONTAIN PROCEED", "Containment Proceeding.", "npc/combine_soldier/vo/containmentproceeding.wav")
Schema.voices.Add("UniversalUnion", "CONTAINED", "Contained.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("UniversalUnion", "CONTROL 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("UniversalUnion", "CONTROLSECTION", "Control section.", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("UniversalUnion", "CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("UniversalUnion", "COPY THAT", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
Schema.voices.Add("UniversalUnion", "COPY", "Copy.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("UniversalUnion", "COPY2", "Copy.", "npc/combine_soldier/vo/copy.wav")
Schema.voices.Add("UniversalUnion", "COULD BE", "Uh, could be.", "npc/metropolice/mc1ans_couldbe.wav")
Schema.voices.Add("UniversalUnion", "COVER ME", "Cover me.", "npc/combine_soldier/vo/coverme.wav")
Schema.voices.Add("UniversalUnion", "COVER", "Cover.", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("UniversalUnion", "COVERED", "We have you covered.", "npc/metropolice/hiding05.wav")
Schema.voices.Add("UniversalUnion", "CP COMPROMISED", "CP is compromised; re-establish.", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("UniversalUnion", "CP ESTABLISH", "CP, we need to establish our perimeter at..", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("UniversalUnion", "CP OVERRUN", "CP is overrun; we have no containment.", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("UniversalUnion", "DAGGER", "DAGGER.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("UniversalUnion", "DASH", "DASH.", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("UniversalUnion", "DB COUNT", "DB count is..", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("UniversalUnion", "DEFENDER", "DEFENDER.", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("UniversalUnion", "DEGREES", "Degrees.", "npc/combine_soldier/vo/degrees.wav")
Schema.voices.Add("UniversalUnion", "DELIVERED", "Delivered.", "npc/combine_soldier/vo/delivered")
Schema.voices.Add("UniversalUnion", "DESERVICED AREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("UniversalUnion", "DESIGNATE SUSPECT", "Designate suspect as.", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("UniversalUnion", "DESIGNATE TARGET", "Designate target as.", "npc/combine_soldier/vo/designatetargetas.wav")
Schema.voices.Add("UniversalUnion", "DESTROY COVER", "Destroy that cover.", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("UniversalUnion", "DISLOCATE INTERPOSE", "Fire to dislocate that interpose.", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("UniversalUnion", "DISMOUNTING HARDPOINT", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("UniversalUnion", "DISP APB", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("UniversalUnion", "DISPLACE", "Displace!", "npc/combine_soldier/vo/displace.wav")
Schema.voices.Add("UniversalUnion", "DISTRIBUTION BLOCK", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("UniversalUnion", "DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("UniversalUnion", "DON'T BE RIDICULOUS", "Don't be ridiculous.", "npc/metropolice/mc1ans_dontberidic.wav")
Schema.voices.Add("UniversalUnion", "DON'T MOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("UniversalUnion", "DON'T WANNA TALK", "I don't wanna talk about it.", "npc/metropolice/mc1ans_dontwannatalk.wav")
Schema.voices.Add("UniversalUnion", "DONT LET HIM", "Don't let him get away!", "npc/metropolice/pointer04.wav")
Schema.voices.Add("UniversalUnion", "DROP YOUR WEAPON", "Drop your weapon, get down!", "npc/metropolice/dropweapon.wav")
Schema.voices.Add("UniversalUnion", "ENGAGING", "Engaging.", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("UniversalUnion", "ENOUGH OUTTA YOU", "That's enough outta you!", "npc/metropolice/mc1ans_enoughouttayou.wav")
Schema.voices.Add("UniversalUnion", "ESCAPE", "You have no chance of escape!", "npc/metropolice/hiding03.wav")
Schema.voices.Add("UniversalUnion", "ESCAPEE", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav")
Schema.voices.Add("UniversalUnion", "ESTABLISH NEW CP", "Fall out, establish a new CP.", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("UniversalUnion", "EVERYTHING I HOPED IT WOULD BE", "This is everything I hoped it would be.", "npc/metropolice/mc1que_everythingihoped.wav")
Schema.voices.Add("UniversalUnion", "EXPIRED", "Expired.", "npc/metropolice/vo/expired.wav")
Schema.voices.Add("UniversalUnion", "EXPOSE TARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("UniversalUnion", "EXTERNAL", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("UniversalUnion", "EXTRACTOR AWAY", "Extractor away!", "npc/combine_soldier/vo/extractoraway.wav")
Schema.voices.Add("UniversalUnion", "EXTRACTOR LIVE", "Extractor is live!", "npc/combine_soldier/vo/extractorislive.wav")
Schema.voices.Add("UniversalUnion", "FASCINATING", "Fascinating.", "npc/metropolice/mc1ans_fascinating.wav")
Schema.voices.Add("UniversalUnion", "FEELING GOOD", "I'm feelin' pretty good about myself today.", "npc/metropolice/mc1que_feelinggood.wav")
Schema.voices.Add("UniversalUnion", "FEET", "My feet're killin' me.", "npc/metropolice/mc1que_feetkillin.wav")
Schema.voices.Add("UniversalUnion", "FIELD PROMOTED", "is field promoted to LEADER-1, holding.", "npc/combine_soldier/vo/isfieldpromoted.wav")
Schema.voices.Add("UniversalUnion", "FIGURES", "Figures.", "npc/metropolice/mc1ans_figures.wav")
Schema.voices.Add("UniversalUnion", "FINAL BACKUP", "Is final team unit backup.", "npc/combine_soldier/vo/isfinalteamunitbackup.wav")
Schema.voices.Add("UniversalUnion", "FINAL VERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("UniversalUnion", "FINAL WARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("UniversalUnion", "FIRST WARNING", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("UniversalUnion", "FIST", "FIST.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("UniversalUnion", "FIX SIGHT LINES", "Fix sight lines, move in.", "npc/combine_soldier/vo/fixsightlinesmovein.wav")
Schema.voices.Add("UniversalUnion", "FLARE DOWN", "Flare down.", "npc/combine_soldier/vo/flaredown.wav")
Schema.voices.Add("UniversalUnion", "FLASH FLASH FLASH", "Five, four, three, two, one, flash flash flash!", "npc/combine_soldier/vo/flashflashflash.wav")
Schema.voices.Add("UniversalUnion", "FLASH", "FLASH.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("UniversalUnion", "FLATLINE", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("UniversalUnion", "FLUSH", "Flush.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("UniversalUnion", "FREE NECROTICS", "I have free necrotics.", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("UniversalUnion", "FREEZE", "Freeze!", "npc/metropolice/freeze.wav")
Schema.voices.Add("UniversalUnion", "FULL ACTIVE", "Full active.", "npc/combine_soldier/vo/fullactive.wav")
Schema.voices.Add("UniversalUnion", "FULL RESPONSE", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav")
Schema.voices.Add("UniversalUnion", "GET DOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("UniversalUnion", "GET IN HERE", "Get in here.", "vo/trainyard/ba_inhere01.wav")
Schema.voices.Add("UniversalUnion", "GET IN", "Get in!", "vo/trainyard/ba_getin.wav")
Schema.voices.Add("UniversalUnion", "GET ON THE GROUND", "Stay where you are! Get on the ground, do it now!", "npc/metropolice/getonground.wav")
Schema.voices.Add("UniversalUnion", "GET OUT", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("UniversalUnion", "GET OUTTA", "Get outta there.", "npc/metropolice/hiding01.wav")
Schema.voices.Add("UniversalUnion", "GETTING 647E", "Still getting that 647-E from local surveillance.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("UniversalUnion", "GETTING A RAISE", "Supposedly we're getting a raise next week.", "npc/metropolice/mc1que_raise.wav")
Schema.voices.Add("UniversalUnion", "GHOST", "GHOST.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("UniversalUnion", "GO ACTIVE", "Go active, intercept!", "npc/combine_soldier/vo/goactiveintercept.wav")
Schema.voices.Add("UniversalUnion", "GO AGAIN", "PT, go again.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("UniversalUnion", "GO ON", "Go on!", "vo/trainyard/ba_goon.wav")
Schema.voices.Add("UniversalUnion", "GO SHARP", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("UniversalUnion", "GO SHARP2", "Go sharp, go sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav")
Schema.voices.Add("UniversalUnion", "GOING IN", "Cover me, I'm goin' in!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("UniversalUnion", "GOT A DB", "Uh, we got a DB here; cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("UniversalUnion", "GOT HIM AGAIN", "Got him again; suspect's 10-20 at..", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("UniversalUnion", "GOT HIM NOW", "Affirmative we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav")
Schema.voices.Add("UniversalUnion", "GOT HIM", "I got him!", "npc/metropolice/shooter02.wav")
Schema.voices.Add("UniversalUnion", "GOT ONE ACCOMPLICE", "I got one accomplice here.", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("UniversalUnion", "GOT SUSPECT ONE", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("UniversalUnion", "GRENADE", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("UniversalUnion", "GRID", "GRID.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("UniversalUnion", "HAD TO GET YOU", "I had to get you for a partner.", "npc/metropolice/mc1ans_hadtopartner.wav")
Schema.voices.Add("UniversalUnion", "HAMMER", "HAMMER.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("UniversalUnion", "HANDS UP", "Hands up.", "npc/metropolice/deploy01.wav")
Schema.voices.Add("UniversalUnion", "HANDS", "Hands.", "npc/metropolice/deploy04.wav")
Schema.voices.Add("UniversalUnion", "HARDEN POSITION", "Harden that position.", "npc/combine_soldier/vo/hardenthatposition.wav")
Schema.voices.Add("UniversalUnion", "HARDPOINT PROSECUTE", "Is at hardpoint; ready to prosecute.", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("UniversalUnion", "HARDPOINT SCANNING", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("UniversalUnion", "HAVE A 10-108", "We have a 10-108.", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("UniversalUnion", "HEAVY RESISTANCE", "Overwatch advise, we have heavy resistance.", "npc/combine_soldier/vo/heavyresistance.wav")
Schema.voices.Add("UniversalUnion", "HELIX", "HELIX.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("UniversalUnion", "HELLUVA MOOD", "You're in a helluva mood.", "npc/metropolice/mc1ans_helluvamood.wav")
Schema.voices.Add("UniversalUnion", "HELP", "Help!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("UniversalUnion", "HERO", "HERO.", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("UniversalUnion", "HES 148", "He's gone 148.", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("UniversalUnion", "HES MINE", "He's mine!", "npc/metropolice/shooter03.wav")
Schema.voices.Add("UniversalUnion", "HIGH PRIORITY", "High-priority region.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("UniversalUnion", "HM", "Hmph.", "npc/metropolice/mc1ans_hm.wav")
Schema.voices.Add("UniversalUnion", "HOLD IT", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("UniversalUnion", "HOLD POSITION", "Protection-team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("UniversalUnion", "HOLD", "Hold it!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("UniversalUnion", "HOLDING AT CODE", "Is holding at code.", "npc/combine_soldier/vo/isholdingatcode.wav")
Schema.voices.Add("UniversalUnion", "HOTPOINT", "Call hotpoint!", "npc/combine_soldier/vo/callhotpoint.wav")
Schema.voices.Add("UniversalUnion", "HUH FIGURES", "Huh, figures.", "npc/metropolice/mc1ans_huhfigures.wav")
Schema.voices.Add("UniversalUnion", "HUNTER", "HUNTER.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("UniversalUnion", "HURRICANE", "HURRICANE.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("UniversalUnion", "HVT", "Overwatch confirm, HVT contained.", "npc/combine_soldier/vo/overwatchconfirmhvtcontained.wav")
Schema.voices.Add("UniversalUnion", "I NEED 10-78", "Dispatch, I need 10-78; officer in trouble!", "npc/metropolice/vo/dispatchineed10-78.wav")
Schema.voices.Add("UniversalUnion", "I SAID MOVE ALONG", "I said move along.", "npc/metropolice/vo/isaidmovealong.wav")
Schema.voices.Add("UniversalUnion", "I SAID MOVE", "I said move!", "vo/trainyard/ba_move01.wav")
Schema.voices.Add("UniversalUnion", "I SEE HIM", "Yes, I see him.", "npc/metropolice/shooter05.wav")
Schema.voices.Add("UniversalUnion", "ICE", "ICE.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("UniversalUnion", "IN POSITION", "In position.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("UniversalUnion", "INBOUND", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("UniversalUnion", "INDUSTRIAL ZONE", "Industrial zone.", "npc/metropolice/vo/industrialzone.wav")
Schema.voices.Add("UniversalUnion", "INFECTION", "Infection.", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("UniversalUnion", "INFESTATION ZONE", "We are in an infestation zone.", "npc/combine_soldier/vo/weareinaninfestationzone.wav")
Schema.voices.Add("UniversalUnion", "INFESTED", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("UniversalUnion", "INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("UniversalUnion", "INOCULATE", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("UniversalUnion", "INTERCEDE", "Intercede.", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("UniversalUnion", "INTERLOCK", "Interlock.", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("UniversalUnion", "INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("UniversalUnion", "INVESTIGATING 10-103", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("UniversalUnion", "ION", "ION.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("UniversalUnion", "IS 10-108", "Is 10-108.", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("UniversalUnion", "IS 10-8", "Unit is 10-8; standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("UniversalUnion", "IS CLOSING", "Is closing on suspect.", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("UniversalUnion", "IS DOWN", "Is down.", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("UniversalUnion", "IS MOVING", "Is moving in.", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("UniversalUnion", "IS PASSIVE", "Is passive.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("UniversalUnion", "IS READY TO GO", "Is ready to go.", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("UniversalUnion", "ISOLATE", "Isolate!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("UniversalUnion", "JET", "JET.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("UniversalUnion", "JUDGE", "JUDGE.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("UniversalUnion", "JUDGEMENT", "Suspect, prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("UniversalUnion", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("UniversalUnion", "JURY", "JURY.", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("UniversalUnion", "JUST THOUGHT OF SOMETHING", "I just thought of something. Uh, wait... maybe not.", "npc/metropolice/mc1que_justthought.wav")
Schema.voices.Add("UniversalUnion", "KEEP MOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("UniversalUnion", "KIDS", "I wouldn't have kids even if they let me.", "npc/metropolice/mc1que_kids.wav")
Schema.voices.Add("UniversalUnion", "KILO", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("UniversalUnion", "KING", "King.", "npc/metropolice/vo/king.wav")
Schema.voices.Add("UniversalUnion", "LAST JOB", "Beats the shit outta my last job.", "npc/metropolice/mc1que_lastjob.wav")
Schema.voices.Add("UniversalUnion", "LAST SEEN AT", "Hiding; last seen at range..", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("UniversalUnion", "LEADER", "LEADER.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("UniversalUnion", "LET ME THINK", "Uh, let me think about that.", "npc/metropolice/mc1ans_letmethink.wav")
Schema.voices.Add("UniversalUnion", "LEVEL 3", "I have a level three civil-privacy violator here.", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("UniversalUnion", "LINE", "LINE.", "npc/metropolice/vo/line.wav")
Schema.voices.Add("UniversalUnion", "LOCATION", "Location?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("UniversalUnion", "LOCK POSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("UniversalUnion", "LOCK", "Lock!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("UniversalUnion", "LOOK OUT", "Look out!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("UniversalUnion", "LOOSE PARASITICS", "Loose parasitics.", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("UniversalUnion", "LOST CONTACT", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("UniversalUnion", "LOW ON", "Running low on verdicts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("UniversalUnion", "LOYALTY CHECK FAILURE", "Patrol, I have a failure to comply with loyalty check, tag as possible 10-103M.", "npc/metropolice/vo/loyaltycheckfailure.wav")
Schema.voices.Add("UniversalUnion", "LOYALTY CHECK", "Uh, roger that, we'll run standard loyalty check procedure 243, my 10-20 to intake station, over.", "npc/metropolice/vo/standardloyaltycheck.wav")
Schema.voices.Add("UniversalUnion", "MACE", "MACE.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("UniversalUnion", "MAINTAIN CP", "All units, maintain this CP.", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("UniversalUnion", "MALCOMPLIANCE", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("UniversalUnion", "MALCOMPLIANT 10-107", "Malcompliant 10-107 at my 10-20; preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("UniversalUnion", "MALIGNANT", "Malignant.", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("UniversalUnion", "MATCH ON APB", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("UniversalUnion", "METERS", "Meters.", "npc/combine_soldier/vo/meters.wav")
Schema.voices.Add("UniversalUnion", "MIGHT BE", "Might be.", "npc/metropolice/mc1ans_mightbe.wav")
Schema.voices.Add("UniversalUnion", "MIGHT NOT", "Might not.", "npc/metropolice/mc1ans_mightnot.wav")
Schema.voices.Add("UniversalUnion", "MINOR HITS", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("UniversalUnion", "MOTION CHECK", "Motion check, all radials!", "npc/combine_soldier/vo/motioncheckallradials.wav")
Schema.voices.Add("UniversalUnion", "MOUTH", "Watch 'yer mouth!", "npc/metropolice/mc1ans_watchyermouth.wav")
Schema.voices.Add("UniversalUnion", "MOVE ALONG", "Move along!", "npc/metropolice/vo/movealong.wav")
Schema.voices.Add("UniversalUnion", "MOVE BACK", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("UniversalUnion", "MOVE IN", "Move in!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("UniversalUnion", "MOVE IT!", "Move it!", "npc/metropolice/vo/moveit.wav")
Schema.voices.Add("UniversalUnion", "MOVE IT", "Move it!", "npc/metropolice/vo/moveit2.wav")
Schema.voices.Add("UniversalUnion", "MOVE", "Move!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("UniversalUnion", "MOVING TO COVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("UniversalUnion", "MOVING TO HARDPOINT", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("UniversalUnion", "NECROTICS", "Necrotics.", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("UniversalUnion", "NEED ANY HELP", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("UniversalUnion", "NEEDS ASSISTANCE", "Officer needs assistance; I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("UniversalUnion", "NEEDS HELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("UniversalUnion", "NEW STUNSTICKS", "I heard we aren't getting those new stunsticks this year.", "npc/metropolice/mc1que_stunsticks.wav")
Schema.voices.Add("UniversalUnion", "NO 647", "Clear; no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("UniversalUnion", "NO CONTACT", "No contact!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("UniversalUnion", "NO IM GOOD", "No, I'm good.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("UniversalUnion", "NO MOVEMENT", "Has negative movement.", "npc/combine_soldier/vo/hasnegativemovement.wav")
Schema.voices.Add("UniversalUnion", "NO POINT IN HIDING", "There's no point in hiding!", "npc/metropolice/hiding02.wav")
Schema.voices.Add("UniversalUnion", "NO VISCON", "No viscon.", "npc/combine_soldier/vo/noviscon.wav")
Schema.voices.Add("UniversalUnion", "NO VISUAL ON", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("UniversalUnion", "NOMAD", "NOMAD.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("UniversalUnion", "NONCITIZEN", "Noncitizen.", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("UniversalUnion", "NONPATROL", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("UniversalUnion", "NONTAGGED VIROMES", "Non-tagged viromes here.", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("UniversalUnion", "NOPE", "Nope.", "npc/metropolice/mc1ans_nope.wav")
Schema.voices.Add("UniversalUnion", "NOT SECURE", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("UniversalUnion", "NOVA", "NOVA.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("UniversalUnion", "NOW GET OUT", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("UniversalUnion", "NOW", "Now.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("UniversalUnion", "ONE DOWN", "One down.", "npc/combine_soldier/vo/onedown.wav")
Schema.voices.Add("UniversalUnion", "OUTBREAK SWARM", "Swarm outbreak in sector.", "npc/combine_soldier/vo/swarmoutbreakinsector.wav")
Schema.voices.Add("UniversalUnion", "OUTBREAK", "Outbreak.", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("UniversalUnion", "OVERWATCH", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("UniversalUnion", "PACIFYING", "Pacifying.", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("UniversalUnion", "PAIN1", "Ugh!", "npc/metropolice/pain1.wav")
Schema.voices.Add("UniversalUnion", "PAIN2", "Uagh!", "npc/metropolice/pain2.wav")
Schema.voices.Add("UniversalUnion", "PAIN3", "Augh!", "npc/metropolice/pain3.wav")
Schema.voices.Add("UniversalUnion", "PAIN4", "Agh!", "npc/metropolice/pain4.wav")
Schema.voices.Add("UniversalUnion", "PARASITES", "We have free parasites.", "npc/combine_soldier/vo/wehavefreeparasites.wav")
Schema.voices.Add("UniversalUnion", "PARASITICS", "Call contact: parasitics.", "npc/combine_soldier/vo/callcontactparasitics.wav")
Schema.voices.Add("UniversalUnion", "PATROL", "PATROL.", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("UniversalUnion", "PAY CUT", "What do you bet we get a pay cut?", "npc/metropolice/mc1que_paycut.wav")
Schema.voices.Add("UniversalUnion", "PEOPLE SUCK", "People suck. Well, except for us I mean.", "npc/metropolice/mc1que_peoplesuck.wav")
Schema.voices.Add("UniversalUnion", "PERKS", "So, you getting the perks they promised you?", "npc/metropolice/mc1que_perks.wav")
Schema.voices.Add("UniversalUnion", "PHANTOM", "PHANTOM.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("UniversalUnion", "PICKUP 647E", "Anyone else pick up a, uh 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("UniversalUnion", "POSITION AT HARDPOINT", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("UniversalUnion", "POSITION CLEAR", "Report all positions clear.", "npc/combine_soldier/vo/reportallpositionsclear.wav")
Schema.voices.Add("UniversalUnion", "POSITION TO CONTAIN", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("UniversalUnion", "POSSIBLE 404", "Possible 404 here.", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("UniversalUnion", "POSSIBLE 647E", "Possible 647-E here; request AirWatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("UniversalUnion", "POSSIBLE ACCOMPLICE", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("UniversalUnion", "POSSIBLE HOSTILES", "Overwatch, reports possible hostiles.", "npc/combine_soldier/vo/overwatchreportspossiblehostiles.wav")
Schema.voices.Add("UniversalUnion", "POSSIBLE LEVEL 3", "Possible level three civil-privacy violator here.", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("UniversalUnion", "PREP CONTACT", "Prep for contact.", "npc/combine_soldier/vo/prepforcontact.wav")
Schema.voices.Add("UniversalUnion", "PREPARE FOR 10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("UniversalUnion", "PREPARING TO JUDGE", "Preparing to judge a 10-107; be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("UniversalUnion", "PRESERVE", "Preserve.", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("UniversalUnion", "PRESSURE", "Pressure.", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("UniversalUnion", "PRIORITY 1", "Confirm; priority-one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("UniversalUnion", "PRIORITY 2", "I have a priority-two anti-citizen here.", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("UniversalUnion", "PRIORITY OBJECTIVE", "Priority One objective.", "npc/combine_soldier/vo/priority1objective.wav")
Schema.voices.Add("UniversalUnion", "PRIVACY", "Yeah, I'm gonna need me some privacy for this!", "vo/trainyard/ba_privacy.wav")
Schema.voices.Add("UniversalUnion", "PRODUCTION BLOCK", "Production-block.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("UniversalUnion", "PROSECUTE MALCOMPLIANT", "Ready to prosecute malcompliant citizen; final warning issued.", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("UniversalUnion", "PROSECUTE", "Prosecute.", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("UniversalUnion", "PROSECUTING", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav")
Schema.voices.Add("UniversalUnion", "PROTECTION", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("UniversalUnion", "QUICK", "Quick.", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("UniversalUnion", "QUICKSAND", "QUICKSAND.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("UniversalUnion", "RANGE", "Range.", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("UniversalUnion", "RANGER", "RANGER.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("UniversalUnion", "RATHER NOT TALK", "I'd rather not talk about that.", "npc/metropolice/mc1ans_rathernottalk.wav")
Schema.voices.Add("UniversalUnion", "RATHER NOT THINK", "Uh, I'd rather not think about that.", "npc/metropolice/mc1ans_rathernotthink.wav")
Schema.voices.Add("UniversalUnion", "RAZOR", "RAZOR.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("UniversalUnion", "READY AMPUTATE", "Ready to amputate.", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("UniversalUnion", "READY CHARGES", "Ready charges.", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("UniversalUnion", "READY EXTRACTORS", "Ready extractors.", "npc/combine_soldier/vo/readyextractors")
Schema.voices.Add("UniversalUnion", "READY JUDGE", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("UniversalUnion", "READY PROSECUTE", "Ready to prosecute.", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("UniversalUnion", "READY WEAPONS", "Ready weapons.", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("UniversalUnion", "READY WEAPONS2", "Ready weapons hostiles inbound.", "npc/combine_soldier/vo/readyweaponshostilesinbound.wav")
Schema.voices.Add("UniversalUnion", "REAPER", "REAPER.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("UniversalUnion", "REINFORCEMENT TEAMS", "Reinforcement-teams, code three.", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("UniversalUnion", "REPORT ALL RADIALS", "Report all radials free.", "npc/combine_soldier/vo/reportallradialsfree.wav")
Schema.voices.Add("UniversalUnion", "REPORT IN", "CP requests all units, uhh Location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("UniversalUnion", "REPORT LOCATION", "All units, report location suspect.", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("UniversalUnion", "REPORT STATUS", "Local CPT, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("UniversalUnion", "REPORTING CLEAR", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("UniversalUnion", "REPURPOSED", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("UniversalUnion", "REQUEST MEDICAL", "Request medical!", "npc/combine_soldier/vo/requestmedical.wav")
Schema.voices.Add("UniversalUnion", "REQUEST REINFORCEMENT", "Overwatch, request reinforcement.", "npc/combine_soldier/vo/overwatchrequestreinforcement.wav")
Schema.voices.Add("UniversalUnion", "REQUEST RESERVE", "Overwatch, request reserve activation.", "npc/combine_soldier/vo/requestreserveactivation.wav")
Schema.voices.Add("UniversalUnion", "REQUEST SKYSHIELD", "Overwatch, request SKYSHIELD.", "npc/combine_soldier/vo/overwatchrequestskyshield.wav")
Schema.voices.Add("UniversalUnion", "REQUEST STIMDOSE", "Request stim-dose!", "npc/combine_soldier/vo/requeststimdose.wav")
Schema.voices.Add("UniversalUnion", "RESIDENTIAL BLOCK", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("UniversalUnion", "RESPOND CODE 3", "All units at location, responding code three.", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("UniversalUnion", "RESPONDING", "Responding.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("UniversalUnion", "RESTRICT", "Restrict.", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("UniversalUnion", "RESTRICTED", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("UniversalUnion", "RESTRICTION ZONE", "Terminal restriction-zone.", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("UniversalUnion", "RIPCORD 2", "Ripcord, ripcord.", "npc/combine_soldier/vo/ripcordripcord.wav")
Schema.voices.Add("UniversalUnion", "RIPCORD", "Ripcord.", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("UniversalUnion", "ROGER THAT", "Roger that.", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("UniversalUnion", "ROLLER", "ROLLER.", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("UniversalUnion", "RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("UniversalUnion", "SACRIFICE CODE", "All units; sacrifice code one and maintain this CP.", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("UniversalUnion", "SAVAGE", "SAVAGE.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("UniversalUnion", "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("UniversalUnion", "SEARCH", "Search.", "npc/metropolice/vo/search.wav")
Schema.voices.Add("UniversalUnion", "SEARCHING FOR SUSPECT", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("UniversalUnion", "SECOND WARNING", "This is your second warning.", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("UniversalUnion", "SECTOR CONTROL", "Stabilization team has sector control.", "npc/combine_soldier/vo/stabilizationteamhassector.wav")
Schema.voices.Add("UniversalUnion", "SECTOR OVERRUN", "Overwatch, sector overrun! Repeat, sector overrun!", "npc/combine_soldier/vo/overwatchsectoroverrun.wav")
Schema.voices.Add("UniversalUnion", "SECTOR SECURE", "Sector is secure, no viscon.", "npc/combine_soldier/vo/sectorissecurenovison.wav")
Schema.voices.Add("UniversalUnion", "SECURE", "Secure.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("UniversalUnion", "SENTENCE", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("UniversalUnion", "SERVE", "Serve.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("UniversalUnion", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("UniversalUnion", "SHOTS FIRED", "Shots fired; hostile malignants here.", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("UniversalUnion", "SHUT UP ABOUT THAT", "Just shut up about that.", "npc/metropolice/mc1ans_shutup.wav")
Schema.voices.Add("UniversalUnion", "SOCIOCIDE", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("UniversalUnion", "SOCIOSTABLE", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("UniversalUnion", "STANDING BY", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("UniversalUnion", "STATIONBLOCK", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("UniversalUnion", "STAY ALERT", "Stay alert, report sight line.", "npc/combine_soldier/vo/stayalertreportsightlines.wav")
Schema.voices.Add("UniversalUnion", "STERILIZE", "Sterilize", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("UniversalUnion", "STICK", "STICK", "npc/metropolice/vo/stick.wav")
Schema.voices.Add("UniversalUnion", "STOMACH", "My stomach is killin' me.", "npc/metropolice/mc1que_stomach.wav")
Schema.voices.Add("UniversalUnion", "STOP WHINING", "Stop whining.", "npc/metropolice/mc1ans_stopwhining.wav")
Schema.voices.Add("UniversalUnion", "STORM RUNOFF", "All units, suspect is in storm runoff system at..", "npc/metropolice/vo/suspectinstormrunoff.wav")
Schema.voices.Add("UniversalUnion", "SUBJECT 505", "Subject is 505.", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("UniversalUnion", "SUBJECT HIGH SPEED", "All units, be advised; subject is now high-speed.", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("UniversalUnion", "SUBJECT", "Subject.", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("UniversalUnion", "SUPPRESSING", "Suppressing.", "npc/combine_soldier/vo/suppressing.wav")
Schema.voices.Add("UniversalUnion", "SURROUNDED", "You're surrounded.", "npc/metropolice/hiding04.wav")
Schema.voices.Add("UniversalUnion", "SUSPECT 11-6", "Suspect 11-6, my 10-20 is..", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("UniversalUnion", "SUSPECT INCURSION", "Disp reports suspect incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("UniversalUnion", "SUSPECT MOVED TO", "Suspect has moved now to..", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("UniversalUnion", "SUSPECT RESTRICTED CANALS", "Suspect is using restricted canals at..", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("UniversalUnion", "SUSPEND", "Suspend.", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("UniversalUnion", "SWEEPING SUSPECT", "Sweeping for suspect.", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("UniversalUnion", "TAG 10-91D", "Tag 10-91d.", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("UniversalUnion", "TAG BUG", "Tag one bug.", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("UniversalUnion", "TAG NECROTIC", "Tag one necrotic.", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("UniversalUnion", "TAG PARASITIC", "Tag one parasitic.", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("UniversalUnion", "TAKE A LOOK", "Going to take a look.", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("UniversalUnion", "TAKE COVER", "Take cover.", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("UniversalUnion", "TAKE HIM DOWN", "Take him down!", "npc/metropolice/takedown.wav")
Schema.voices.Add("UniversalUnion", "TAP", "TAP.", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("UniversalUnion", "TARGET 1", "Call contact: suspect target one.", "npc/combine_soldier/vo/callcontacttarget1.wav")
Schema.voices.Add("UniversalUnion", "TARGET COMPROMISED", "Target compromised, move in.", "npc/combine_soldier/vo/targetcompromisedmovein.wav")
Schema.voices.Add("UniversalUnion", "TARGET CONTACT AT", "Target contact at..", "npc/combine_soldier/vo/targetcontactat.wav")
Schema.voices.Add("UniversalUnion", "TARGET MY RADIAL", "Target my radial!", "npc/combine_soldier/vo/targetmyradial.wav")
Schema.voices.Add("UniversalUnion", "TARGET STERILIZED", "Overwatch, target one sterilized.", "npc/combine_soldier/vo/overwatchtarget1sterilized.wav")
Schema.voices.Add("UniversalUnion", "TEAM ADVANCE", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("UniversalUnion", "TEAM DEPLOYED", "Team is deployed and scanning.", "npc/combine_soldier/vo/teamdeployedandscanning.wav")
Schema.voices.Add("UniversalUnion", "TEAM DOWN", "Overwatch, team is down, sector is not controlled.", "npc/combine_soldier/vo/overwatchteamisdown.wav")
Schema.voices.Add("UniversalUnion", "THERE HE GOES", "There he goes! He's at..", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("UniversalUnion", "THERE HE IS", "There he is!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("UniversalUnion", "THERES YOUR PROBLEM", "There's 'yer problem, right there.", "npc/metropolice/mc1ans_theresyerproblem.wav")
Schema.voices.Add("UniversalUnion", "THINK SO", "Think so.", "npc/metropolice/mc1ans_thinkso.wav")
Schema.voices.Add("UniversalUnion", "THIS IS RIDICULOUS", "This is ridiculous.", "npc/metropolice/mc1que_thisridiculous.wav")
Schema.voices.Add("UniversalUnion", "TRANSITBLOCK", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("UniversalUnion", "TROUBLE", "Lookin' for trouble.", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("UniversalUnion", "UNDER FIRE", "Officer under fire; taking cover.", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("UniversalUnion", "UNION", "UNION.", "npc/metropolice/vo/union.wav")
Schema.voices.Add("UniversalUnion", "UNIT CLOSING", "Unit is closing.", "npc/combine_soldier/vo/unitisclosing.wav")
Schema.voices.Add("UniversalUnion", "UNIT IN", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("UniversalUnion", "UNIT IS 10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("UniversalUnion", "UNKNOWN", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("UniversalUnion", "UP THERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("UniversalUnion", "UPI", "UPI.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("UniversalUnion", "UTL SUSPECT", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav")
Schema.voices.Add("UniversalUnion", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("UniversalUnion", "VACATE", "Vacate, citizen.", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("UniversalUnion", "VERDICT", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("UniversalUnion", "VICE", "VICE.", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("UniversalUnion", "VICTOR", "VICTOR.", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("UniversalUnion", "VISCON", "Viscon!", "npc/combine_soldier/vo/viscon.wav")
Schema.voices.Add("UniversalUnion", "WARNING GIVEN", "Second warning given.", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("UniversalUnion", "WASTERIVER", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("UniversalUnion", "WATCH IT", "Watch it!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("UniversalUnion", "WEAPON OFF", "Weapons off safe, prep for contact.", "npc/combine_soldier/vo/weaponsoffsafeprepforcontact.wav")
Schema.voices.Add("UniversalUnion", "WEAPON READY", "In position, weapon ready.", "npc/metropolice/vo/inpositiononeready.wav")
Schema.voices.Add("UniversalUnion", "WHAT THE HELL", "What the hell?", "npc/metropolice/surprise4.wav")
Schema.voices.Add("UniversalUnion", "WHAT THE", "What the-?", "npc/metropolice/surprise1.wav")
Schema.voices.Add("UniversalUnion", "WORKFORCE", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("UniversalUnion", "WRAP UP", "Thats it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("UniversalUnion", "XRAY", "XRAY.", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("UniversalUnion", "YEAH", "Yeah.", "npc/metropolice/mc1ans_yeah.wav")
Schema.voices.Add("UniversalUnion", "YELLOW", "YELLOW.", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("UniversalUnion", "YEP", "Yep.", "npc/metropolice/mc1ans_yep.wav")
Schema.voices.Add("UniversalUnion", "YOU CAN GO", "Alright; you can go.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("UniversalUnion", "YOUR WIFE", "Your wife doesn't like me, does she?", "npc/metropolice/mc1que_yourwife.wav")
Schema.voices.Add("UniversalUnion", "ZONE", "Zone.", "npc/metropolice/vo/zone.wav")
Schema.voices.Add("UniversalUnion", "ALL UNITS CODE", "All units code.", "npc/metropolice/vo/allunitscode.wav")
Schema.voices.Add("UniversalUnion", "CLOSING ON SUSPECT", "Closing on suspect.", "npc/metropolice/vo/closingonsuspect.wav")
Schema.voices.Add("UniversalUnion", "CONTROL 100 LOCATION", "Control is one-hundred percent this location.", "npc/metropolice/vo/controlis100percent.wav")
Schema.voices.Add("UniversalUnion", "INVESTIGATING", "Investigating.", "npc/metropolice/vo/investigating.wav")
Schema.voices.Add("UniversalUnion", "NEED AIRWATCH", "Dispatch, we need AirWatch.", "npc/metropolice/vo/dispweneedairwatch.wav")
Schema.voices.Add("UniversalUnion", "NEGATIVE", "Negative.", "npc/metropolice/vo/negative.wav")
Schema.voices.Add("UniversalUnion", "NEGATIVE2", "Negative.", "npc/metropolice/vo/negative1.wav")
Schema.voices.Add("UniversalUnion", "NO SIGN 647E", "No sign of that 647-E.", "npc/metropolice/vo/nosignofthat647e.wav")
Schema.voices.Add("UniversalUnion", "PROTECTION TEAMS", "Protection teams", "npc/metropolice/vo/protectionteams.wav")
Schema.voices.Add("UniversalUnion", "REPORT IN", "Report in.", "npc/metropolice/vo/reportin.wav")
Schema.voices.Add("UniversalUnion", "ALL UNITS LOCATION", "All units report location.", "npc/metropolice/vo/reportlocation.wav")
Schema.voices.Add("UniversalUnion", "REPORT STATUS2", "Report status.", "npc/metropolice/vo/reportstatus.wav")
Schema.voices.Add("UniversalUnion", "RESPONDING CODE 2", "Responding code two.", "npc/metropolice/vo/respondingcode2.wav")
Schema.voices.Add("UniversalUnion", "SUSPECT", "Suspect.", "npc/metropolice/vo/suspect.wav")
Schema.voices.Add("UniversalUnion", "SPEAR", "SPEAR.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("UniversalUnion", "PAYBACK", "PAYBACK.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("UniversalUnion", "SWORD", "SWORD.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("UniversalUnion", "STORM", "STORM.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("UniversalUnion", "STRIKER", "STRIKER.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("UniversalUnion", "UNIFORM", "UNIFORM.", "npc/combine_soldier/vo/uniform.wav")