Schema.voices.Add("Vortigaunt", "ACCOMPANY", "Gladly we accompany.", "vo/npc/vortigaunt/accompany.wav")
Schema.voices.Add("Vortigaunt", "AFFIRMED", "Affirmed.", "vo/npc/vortigaunt/affirmed.wav")
Schema.voices.Add("Vortigaunt", "ALL IN ONE", "All in one then one in all.", "vo/npc/vortigaunt/allinoneinall.wav")
Schema.voices.Add("Vortigaunt", "ALLOW ME", "Allow me.", "vo/npc/vortigaunt/allowme.wav")
Schema.voices.Add("Vortigaunt", "AS YOU WISH", "As you wish.", "vo/npc/vortigaunt/asyouwish.wav")
Schema.voices.Add("Vortigaunt", "BE OF SERVICE", "Can we be of service?", "vo/npc/vortigaunt/beofservice.wav")
Schema.voices.Add("Vortigaunt", "CAUTION", "Caution.", "vo/npc/vortigaunt/caution.wav")
Schema.voices.Add("Vortigaunt", "CERTAINLY", "Certainly.", "vo/npc/vortigaunt/certainly.wav")
Schema.voices.Add("Vortigaunt", "DONE", "Done.", "vo/npc/vortigaunt/done.wav")
Schema.voices.Add("Vortigaunt", "DREAMED", "We have dreamed of this moment.", "vo/npc/vortigaunt/dreamed.wav")
Schema.voices.Add("Vortigaunt", "EMPOWER US", "Empower us.", "vo/npc/vortigaunt/empowerus.wav")
Schema.voices.Add("Vortigaunt", "GLADLY", "Gladly.", "vo/npc/vortigaunt/gladly.wav")
Schema.voices.Add("Vortigaunt", "HALT", "Halt.", "vo/npc/vortigaunt/halt.wav")
Schema.voices.Add("Vortigaunt", "HERE", "Here.", "vo/npc/vortigaunt/here.wav")
Schema.voices.Add("Vortigaunt", "FEAR FAILED", "We fear we have failed.", "vo/npc/vortigaunt/fearfailed.wav")
Schema.voices.Add("Vortigaunt", "FREEMAN", "Freeman.", "vo/npc/vortigaunt/freeman.wav")
Schema.voices.Add("Vortigaunt", "GLADLY", "Gladly.", "vo/npc/vortigaunt/gladly.wav")
Schema.voices.Add("Vortigaunt", "AN HONOR", "It is an honor.", "vo/npc/vortigaunt/itishonor.wav")
Schema.voices.Add("Vortigaunt", "YES", "Yes.", "vo/npc/vortigaunt/yes.wav")
Schema.voices.Add("Vortigaunt", "TAKE US", "Freeman take us with you.", "vo/npc/vortigaunt/takeus.wav")
Schema.voices.Add("Vortigaunt", "FOR FREEDOM", "For freedom.", "vo/npc/vortigaunt/forfreedom.wav")
Schema.voices.Add("Vortigaunt", "WITH PLEASURE", "With pleasure.", "vo/npc/vortigaunt/pleasure.wav")
Schema.voices.Add("Vortigaunt", "GLORIOUS END", "To our glorious end.", "vo/npc/vortigaunt/gloriousend.wav")
Schema.voices.Add("Vortigaunt", "HOLD STILL", "Hold still.", "vo/npc/vortigaunt/holdstill.wav")
Schema.voices.Add("Vortigaunt", "LEAD US", "Lead us.", "vo/npc/vortigaunt/leadus.wav")
Schema.voices.Add("Vortigaunt", "HONOR FOLLOW", "To our honor we follow you.", "vo/npc/vortigaunt/honorfollow.wav")
Schema.voices.Add("Vortigaunt", "TO THE VOID", "To the void with you.", "vo/npc/vortigaunt/tothevoid.wav")
Schema.voices.Add("Vortigaunt", "VORT1", "Ahg lah.", "vo/npc/vortigaunt/vortigese02.wav")
Schema.voices.Add("Vortigaunt", "VORT2", "Targh.", "vo/npc/vortigaunt/vortigese03.wav")
Schema.voices.Add("Vortigaunt", "VORT3", "Langh.", "vo/npc/vortigaunt/vortigese05.wav")
Schema.voices.Add("Vortigaunt", "VORT4", "Gahn.", "vo/npc/vortigaunt/vortigese07.wav")
Schema.voices.Add("Vortigaunt", "VORT5", "Galanga.", "vo/npc/vortigaunt/vortigese08.wav")
Schema.voices.Add("Vortigaunt", "VORT6", "Galalangh.", "vo/npc/vortigaunt/vortigese09.wav")
Schema.voices.Add("Vortigaunt", "VORT7", "Cher ganlahn cher alagahn.", "vo/npc/vortigaunt/vortigese11.wav")
Schema.voices.Add("Vortigaunt", "VORT8", "Cher langh gahn chaleng gur.", "vo/npc/vortigaunt/vortigese12.wav")
Schema.voices.Add("Vortigaunt", "VORT9", "Ter langh gur chaleng chur langh lerr.", "vo/npc/vortigaunt/vortigese13.wav")